/*
MIT License

Copyright (c) 2026 Misael Monterroca

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// This example opens an existing .pptx — template.pptx, generated by
// python-pptx (a real, foreign producer, not pptxgo's own output — see
// pptx/testdata's own fixtures for why that distinction matters), inspects
// its {{placeholder}} tokens, merges in real values, and saves the result.
// Every part this program never touches (the theme, slide masters/layouts,
// the second "Thank you" slide) passes through byte-for-byte unmodified.
package main

import (
	"log"
	"os"

	"github.com/mmonterroca/pptxgo/pptx"
)

func main() {
	tmpl, err := pptx.Open("template.pptx")
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("opened template.pptx: %d slide(s)", tmpl.SlideCount())

	names, err := tmpl.PlaceholderNames()
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("placeholders found: %v", names)

	n, err := tmpl.Merge(pptx.MergeData{
		"client_name":   "Acme Corp",
		"contact_email": "sales@acme.example",
	}, pptx.WithStrictMode())
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("substituted %d placeholder(s)", n)

	s1, err := tmpl.Slide(1)
	if err != nil {
		log.Fatal(err)
	}
	text, err := s1.Text()
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("slide 1 text after merge:\n%s", text)

	f, err := os.Create("02_read_and_modify_out.pptx")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	if err := tmpl.Save(f); err != nil {
		log.Fatal(err)
	}
}
